# Generated by Django 5.0.4 on 2024-05-12 10:30

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_postimage_file_id_alter_post_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=apps.core.fields.OSMPointField(default=None, srid=4326),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=820),
        ),
    ]
