# Generated by Django 5.0.6 on 2024-05-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='license_plate',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
