# Generated by Django 5.0.6 on 2024-05-15 16:58

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_post_license_plate_post_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=apps.core.fields.OSMPointField(blank=True, null=True, srid=4326),
        ),
    ]
