# Generated by Django 5.0.6 on 2024-06-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_post_bot_message_id_alter_post_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='file',
            field=models.FileField(upload_to='photos/%Y/%m/%d', verbose_name='File'),
        ),
    ]
