# Generated by Django 5.0.6 on 2024-06-14 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_alter_postcomment_text_alter_postimage_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='photos/%Y/%m/%d', verbose_name='File')),
                ('file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram bot file id')),
                ('file_type', models.CharField(choices=[('img', 'Image'), ('vid', 'Video')], default='img', max_length=24, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='Post')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
