# Generated by Django 5.0.4 on 2024-05-06 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_violator_alter_category_options_category_violator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='violator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='category.violator'),
        ),
    ]
