# Generated by Django 5.0.6 on 2024-06-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_name_en_category_name_kg_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_kg',
            new_name='name_ky',
        ),
        migrations.RenameField(
            model_name='violator',
            old_name='name_kg',
            new_name='name_ky',
        ),
    ]
