# Generated by Django 5.0.6 on 2024-06-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_rename_name_kg_category_name_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='violator',
            name='name_en',
        ),
    ]
