# Generated by Django 5.0.6 on 2024-06-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_remove_category_name_en_remove_violator_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='violator',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
