# Generated by Django 5.0.6 on 2024-05-31 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customtoken'),
        ('authtoken', '0004_alter_tokenproxy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customtoken',
            options={},
        ),
        migrations.RemoveField(
            model_name='customtoken',
            name='created',
        ),
        migrations.RemoveField(
            model_name='customtoken',
            name='key',
        ),
        migrations.RemoveField(
            model_name='customtoken',
            name='user',
        ),
        migrations.AddField(
            model_name='customtoken',
            name='token_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token'),
            preserve_default=False,
        ),
    ]
