# Generated by Django 5.0.6 on 2024-07-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_botadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tg_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Telegram chat id'),
        ),
    ]
